### ISSUE TITLE
how to improve the quality of the results

### ISSUE THREAD

**Issue by zhaoyue99** [wd1511/PDNLA-Net#2]
Thanks for your work! I tried to test some images with the pre-trained model you shared. Are there any parameters that can be adjusted to improve the quality of the results? Thank you very much!

**Comment by Fadexboss** [comment]
Can you share your e-mail account with me? I want to ask you something and I know a solution that can increase the original video quality.

**Comment by wd1511** [comment]
If the task you are working on here is a colorization task based on reference images, and you encounter poor results, it may be due to the choice of reference images not being suitable enough. We have also mentioned this in the limitations section, and we have showcased some results in [[results](https://drive.google.com/drive/folders/1qkb668XB4EY7Hc0n3Sb5KBjYVELiON8u)].
If you are working on a video colorization task, it's possible that all existing reference-based colorization methods may not be very suitable for video colorization tasks. This could be due to issues such as the model being too large and lacking real-time inference speed. We recommend choosing a more lightweight base model in such cases.

**Comment by zhaoyue99** [comment]
> If the task you are working on here is a colorization task based on reference images, and you encounter poor results, it may be due to the choice of reference images not being suitable enough. We have also mentioned this in the limitations section, and we have showcased some results in [[results](https://drive.google.com/drive/folders/1qkb668XB4EY7Hc0n3Sb5KBjYVELiON8u)]. If you are working on a video colorization task, it's possible that all existing reference-based colorization methods may not be very suitable for video colorization tasks. This could be due to issues such as the model being too large and lacking real-time inference speed. We recommend choosing a more lightweight base model in such cases.

Thank you very much for your reply! In the follow-up test, I will try to change the reference images to improve the quality of the results.
